### ISSUE TITLE
发现个问题, 当全屏视频的时候  通知不是在顶部,还是在原来的位置...

### ISSUE THREAD

**Issue by holyen** [zhengwenming/WMPlayer#1]

**Comment by anhuijhy** [comment]
估计他是通过 改frame 而不是转屏。所以有这个问题，代码我还没看

**Comment by zhengwenming** [comment]
首先很感谢你们提出的问题，我会尽快修改。我旋转的UIView，并不是真正意义上的旋转屏幕。所以有这个bug存在。我现在尝试做屏幕的真正旋转，谢谢你们的关注和支持。

**Comment by zhengwenming** [comment]
bug已经解决，请更新最新的代码。
