### ISSUE TITLE
播放时长为小数时，视频提前退出

### ISSUE THREAD

**Issue by shxlxa** [zhengwenming/WMPlayer#109]
你好，我用WMPlayer播放视频时，发现如果实际视频时长8.5秒时（实际显示总时长8秒），视频播到8秒的时候就停止播放了，有什么办法改进吗？能不能改进进度条的精度。多谢！

**Comment by zhengwenming** [comment]
应该是我设置的每秒走一次进度的原因。这里可以改，修改一个GCD的1s为0.5s就可以了。
