### ISSUE TITLE
WMPlayer视频播放器一个小Bug

### ISSUE THREAD

**Issue by iGhibli** [zhengwenming/WMPlayer#11]
使用您的WMPlayer视频播放器源码，在6plus上cell中播放视频是没问题的，但在小屏幕中（如iPhone5）上播放时，点击播放cell上的playBtn并不隐藏，强制隐藏会造成cell复用时其他cell没有playBtn按钮显示。

**Comment by zhengwenming** [comment]
首先感谢你的使用，使用中遇到问题，群里联系我群：487599875，把demo发给我邮箱 740747055@qq
.com
我会尽力帮你fix bug。
