### ISSUE TITLE
怎么进行无缝循环播放 我在播放完毕之后直接开始播放没效果

### ISSUE THREAD

**Issue by ichenwanbing** [zhengwenming/WMPlayer#114]

**Comment by zhengwenming** [comment]
您好，您可要研究https://github.com/zhengwenming/WMQueuePlayer这个，开发中。。。 完成度 90%

**Comment by zhengwenming** [comment]
你也可以在播放完成的代理事件里面重新resetWMPlayer，然后传同一个model视频资源进去，最后调用play。这样就可以循环播放了。
