### ISSUE TITLE
WMDragView 集成到 WMPlayer

### ISSUE THREAD

**Issue by veryitman** [zhengwenming/WMPlayer#115]
使用 github 上面最新的 WMPlayer 示例, 将其继承的子类改为 WMDragView 后, 腾讯视频页面小屏幕播放视频, 拖拽无法自由移动, 无论移动小屏幕到什么地方, 最终会回到屏幕的左上角或者右上角哪里?

之前版本的 WMPlayer 没有这个问题.

**Comment by zhengwenming** [comment]
你要研究一下WMDragView的用法，另外WMPlayer更新到5.0了，麻烦请更新一下，如有问题，及时联系我本人
