### ISSUE TITLE
报错Error Domain=AVFoundationErrorDomain Code=-11828 "打不开" 

### ISSUE THREAD

**Issue by zhanqin** [zhengwenming/WMPlayer#116]
具体情况是，同一个视频，第一次可以正常播放，第二次再播放的时候或报错，报错信息为：Error Domain=AVFoundationErrorDomain Code=-11828 "打不开" UserInfo={NSUnderlyingError=0x17025e510 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}, NSLocalizedFailureReason=不支持此媒体的格式。, NSLocalizedDescription=打不开}
这个问题目前只发现在6s和7p iOS10.3.3上出现了，请问怎么解决？

**Comment by zhengwenming** [comment]
母鸡哦。。。。。

**Comment by zhangyuhan18** [comment]
> 具体情况是，同一个视频，第一次可以正常播放，第二次再播放的时候或报错，报错信息为：Error Domain=AVFoundationErrorDomain Code=-11828 "打不开" UserInfo={NSUnderlyingError=0x17025e510 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}, NSLocalizedFailureReason=不支持此媒体的格式。, NSLocalizedDescription=打不开}
> 这个问题目前只发现在6s和7p iOS10.3.3上出现了，请问怎么解决？

你好请问问题解决了吗？我也遇到了，求解
