### ISSUE TITLE
播放在线直播m3u8 视频 播放暂停问题

### ISSUE THREAD

**Issue by hellcall** [zhengwenming/WMPlayer#119]
进入直播视频界面 进入后就触发[wmplayer play]方法 但是视频出于暂停状态  需要再次点击播放按钮才播放

**Comment by wangzelongQM** [comment]
这个问题你解决了吗?

**Comment by zhangchangrui** [comment]
这个问题有答案吗 我的也存在这个问不知道怎么解决

**Comment by wangzelongQM** [comment]
我的视频格式是m3u8的,放在大神的工程里面没有这个问题,点开就可以自动播放,但是我自己新建的工程集成这个播放器就不能自动播放了,郁闷!

**Comment by zhengwenming** [comment]
注意看readme，里面有答案，也给了博客链接。

**Comment by zhengwenming** [comment]
升级iOS10后,AVPlayer有时候播放不了的问题

参考以下链接 http://blog.csdn.net/viiimaus/article/details/54926022 https://developer.apple.com/reference/avfoundation/avplayer/1643482-automaticallywaitstominimizestal
