### ISSUE TITLE
iOS 11 全屏后进度条超出屏幕边界,无法点击到缩小按钮

### ISSUE THREAD

**Issue by wangkai1988** [zhengwenming/WMPlayer#120]
如题,大神快来更新一波

**Comment by shxlxa** [comment]
是的，我也发现这个问题了

**Comment by shxlxa** [comment]
@wangkai1988 哥们，全屏更新约束的时候，topView和bottomView都少了一个约束，自己加上就可以了

**Comment by zhengwenming** [comment]
已经更新，适配iOS 11、适配iPhone X，请更新。谢谢。

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
