### ISSUE TITLE
push 再返回后 菊花图不消失

### ISSUE THREAD

**Issue by yangjingdj** [zhengwenming/WMPlayer#122]
直接进入播放没有问题，当页面push一次后，再返回到播放页面，菊花图就一直显示  不消失

**Comment by zhengwenming** [comment]
没有遇到过这个bug，请整个demo发给我QQ邮箱，740747055@qq.com。谢谢！

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
