### ISSUE TITLE
Dependency Analysis Error Group

### ISSUE THREAD

**Issue by TongFangyuan** [zhengwenming/WMPlayer#124]
<img width="630" alt="bug" src="https://user-images.githubusercontent.com/9019860/32153096-6249fb48-bcf6-11e7-8924-d5529bb8e3b2.png">

hello,我在集成您的项目的时候,遇见这个问题,请问怎么解决呢,谢谢~

**Comment by TongFangyuan** [comment]
cocopods 导入的,看了之前的 issue 导入的是 3.0.6,无法导入最新的?

**Comment by zhengwenming** [comment]
pods没有搞好，我的锅，请暂时使用拖入文件的方式集成WMPlayer，文件并不是大，轻量级的。

**Comment by zhengwenming** [comment]
cocoapods已经更新，而且是最新版本5.0的，请更新，久等了，老铁。谢谢支持
