### ISSUE TITLE
bugly ，检测报这个奔溃信息，奔溃率，很高

### ISSUE THREAD

**Issue by aihuimoushuixiao** [zhengwenming/WMPlayer#125]
An AVPlayerItem cannot be associated with more than one instance of AVPlayer

**Comment by zhengwenming** [comment]
大概意思就是：一个AVPlayerItem对象不能同时绑定到多个AVPlayer对象身上；
解释：一对一，一个AVPlayerItem对象只能和一个AVPlayer对应，如果重新播放或者重新进来页面，那么必须释放之前的旧的AVPlayerItem对象，创建一个新的AVPlayerItem，如果不释放，那么崩溃是必然的，释放的方法demo中已经提供，所以检查一下你释放了播放器没？
