### ISSUE TITLE
FastForwardView.xib找不到

### ISSUE THREAD

**Issue by lypcliuli** [zhengwenming/WMPlayer#126]
报错信息：
reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/88A97FCC-7448-4B51-B4A7-45390C9BC39C/TestLabel.app> (loaded)' with name 'FastForwardView''

使用方式：
pod 'WMPlayer', '~> 3.0.6'
install下来之后 pods下的WMPlayer文件中有FastForwardView.xib文件，show in finder也存在，iPhone SE iOS11.0.3运行

**Comment by STlixinfan** [comment]
我也遇到了同样的问题。找到解决办法了么？

**Comment by appleboyguoli** [comment]
self.FF_View = [[[NSBundle bundleForClass:[self class]] loadNibNamed:@"FastForwardView" owner:self options:nil] lastObject];
改成这样就OK啦，主要是cocospod中引用NSBundle资源的问题

**Comment by zhaokaihan** [comment]
我直接编译就不通过，请问这是什么问题

**Comment by zhaokaihan** [comment]
Unable to run command 'StripNIB FastForwardView.nib' - this target might include its own product.
Unable to run command 'StripNIB FastForwardView~iphone.nib' - this target might include its own product.
Unable to run command 'StripNIB FastForwardView~ipad.nib' - this target might include its own product.

**Comment by ilioner** [comment]
所以请问怎么解决呢，模拟器还是不行

**Comment by RowlingZhang** [comment]
没有通过cocoapods，手动导入就没有这个问题了。

**Comment by zhengwenming** [comment]
cocoapods已经更新，从根本上解决了上面的所有问题，而且是最新版本5.0，谢谢大家支持。
