### ISSUE TITLE
解决了滑动slide时卡顿的问题

### ISSUE THREAD

**Issue by shanchaojie** [zhengwenming/WMPlayer#13]
首先,非常感谢作者的无私奉献,拿出来这么好的东西开源.该项目也是我非常欣赏的项目之一.我在使用过程中发现有出现滑动slide时,有一些卡顿现象.用了一些时间仔细分析了造成的原因是在滑动时,计时器仍然运行造成,滑动的slide与计时器的slide不匹配,造成卡顿.幸运的是,我找到了解决方案.所以拿来给大家分享一下.附件为我改过的文件上传,不为别的,也希望能像作者一样帮助更多的人.
[VMPlayDemo.zip](https://github.com/zhengwenming/WMPlayer/files/234397/VMPlayDemo.zip)

**Comment by AndyLeeBlue** [comment]
效果很好，已经用了，赞！

**Comment by zhengwenming** [comment]
很感谢你的代码，我已经把你的代码放到项目中了，bug解决了。谢谢你的支持。为你点赞。

**Comment by QDDLoveIT** [comment]
进度条拖拽一点,之后视频正常播放,进度条不再移动了

**Comment by zhengwenming** [comment]
#pragma mark
#pragma mark--开始点击sidle
- (void)stratDragSlide:(UISlider *)slider{
//    self.isDragingSlider = YES;
    self.isDragingSlider = NO;

}
改成这样对吗？你的意思是这里为NO，对吧？
