### ISSUE TITLE
缓冲区有足够数据但是仍然不能播放

### ISSUE THREAD

**Issue by CodeWCJ** [zhengwenming/WMPlayer#130]
当播放的位置达到缓冲区的位置后，会转菊花，来缓冲，缓冲区有足够数据,虽然菊花停止转了，但是之后并不会自动播放，在监听状态的方法里[keyPath isEqualToString:@"playbackBufferEmpty"]时， 调用了[self loadedTimeRanges];这个方法，dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self play];
    
        [self.loadingView stopAnimating];
    });在主线程隔5秒播放，play的方法是调用了，但还是不会播放

**Comment by zhengwenming** [comment]
试试看是不是这个属性影响的
self.player.automaticallyWaitsToMinimizeStalling = NO;//or  YES
，如果不是再联系我，谢谢。

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人

**Comment by rryan2** [comment]
5.1好像又出现了这个问题 用5.0解决了
