### ISSUE TITLE
视频播放不成功

### ISSUE THREAD

**Issue by xiayige** [zhengwenming/WMPlayer#132]
文明大神，我用了你的视频框架，一开始没有任何问题，最近出现一个奇葩问题，就是视频在分享到QQ或微信，然后返回APP，重新加载视频，15次以上就会报视频加载失败，视频的资源是没有问题的，求大神帮忙解答，谢谢了。。。

**Comment by zhengwenming** [comment]
给我个demo吧，不然我束手无策，爱莫能助啊！

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
