### ISSUE TITLE
屏幕旋转后全屏的按钮不可点击

### ISSUE THREAD

**Issue by BaoLeiLi** [zhengwenming/WMPlayer#137]
您好，我全屏后，返回按钮和暂停以及进度条都正常，但是全屏的按钮不能点击了，我是通过下面这种方式全屏的
[[UIDevice currentDevice] setValue:[NSNumber numberWithInteger:UIInterfaceOrientationLandscapeRight] forKey:@"orientation"];

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
