### ISSUE TITLE
视频切换问题

### ISSUE THREAD

**Issue by lushengfu** [zhengwenming/WMPlayer#140]
为什么在切换视频的时候,要奖WMPlayer设置为nil,直接更换播放源URL为什么不行?

**Comment by zhengwenming** [comment]
有两种方式切换视频源
1、把当前旧的WMPlayer播放器对象释放，wmPlayer = nil;然后重新alloc init一个新的播放器对象，传入新model，调用paly方法播放。
2、直接调用resetWMPlayer方法，重置一下里面的参数、model、还有视频资源item等等，最后传入新model，调用paly方法播放。此方法不需要把播放器对象设置为nil，但是一定要去清空一下里面的东东。

**Comment by lushengfu** [comment]
收到
