### ISSUE TITLE
。。

### ISSUE THREAD

**Issue by Crayonnerry** [zhengwenming/WMPlayer#143]

**Comment by Crayonnerry** [comment]
我用你demo中的代码然后自己写了个demo为啥 上面 暂停 单次点击屏幕什么的代理都不走的。。。？？？

**Comment by zhengwenming** [comment]
Demo都是好好的额，那已经证明你自己不会用，不是bug好多，不是bug好多，不是bug好多！

**Comment by Crayonnerry** [comment]
我意思是在用的时候产生的bug好多。。不是你的demo本身的bug....

**Comment by zhengwenming** [comment]
代理func不相应，可能是wmpalyer的父视图superView是imageView的原因。如果是，打开imageView的交互即可。我猜测是这样引起的，你仔细检查一下。

**Comment by Crayonnerry** [comment]
好的，我试试看，谢谢。
