### ISSUE TITLE
有没有记录播放视频进度的功能??

### ISSUE THREAD

**Issue by lilovexin** [zhengwenming/WMPlayer#147]

**Comment by zhengwenming** [comment]
播放器本身的职责是播放，不会牵涉到业务逻辑进来，记录播放的进度需要开发者自己实现，然后设置WMPlayerModel的seekTime属性，就可以直接跳转到上次播放的地方继续播放了。
1、提供一点点思路。你可以简单的处理，播放进度存在model或者NSUserDefaults里，页面消失，或者关闭播放器的时候，我是提供了API的，wmPlayer.currentTime直接获取到当前播放到哪了，存起来，下次进来取出你存的值，然后直接设置model.seekTime就可以了
2、接口实现。调用自己服务器的接口，把你当前播放的视频的id和进度提交后台记录，下次进来播放，先调用接口，看看有没有播放过，播放过就获取时间，设置model.seekTime就OK了。
总上所述；就是记录问题，是后台记录，还是你自己本地处理。WMPlayer只提供你seekTime和获取当前播放的时间点API。
