### ISSUE TITLE
如何进行视频的循环播放和禁止控制页面的出现

### ISSUE THREAD

**Issue by zhangfurun** [zhengwenming/WMPlayer#149]
如题

**Comment by zhengwenming** [comment]
如果不需要控制view层，可以用一句代码移除掉，就OK了。
    [((UIView *)[self.wmPlayer valueForKey:@"contentView"]).subviews makeObjectsPerformSelector:@selector(removeFromSuperview)];

视频循环，在播放完成的代理里面去resetWMPLay，然后play同一个model就可以了
