### ISSUE TITLE
严重bug

### ISSUE THREAD

**Issue by q351941406** [zhengwenming/WMPlayer#165]
swift UIWebView.
我的UIWebView在浏览youku的时候无法横屏播放,把你的库删掉后就行了,只要这库放在工程下就会有影响.

**Comment by zhengwenming** [comment]
把category的.m中的旋转VC的系统方法重写为这样既可解决。
// 是否支持自动转屏
- (BOOL)shouldAutorotate{
    NSString *className = NSStringFromClass(self.class);
    if ([@[@"AVPlayerViewController", @"AVFullScreenViewController", @"AVFullScreenPlaybackControlsViewController"
           ] containsObject:className]) {
        return YES;
    }
    return NO;
}
// 支持哪些屏幕方向
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    NSString *className = NSStringFromClass(self.class);
    if ([@[@"AVPlayerViewController", @"AVFullScreenViewController", @"AVFullScreenPlaybackControlsViewController"
           ] containsObject:className]) {
        return UIInterfaceOrientationMaskAllButUpsideDown;
    }
    return UIInterfaceOrientationMaskPortrait;
}
