### ISSUE TITLE
云盘下载的ffmpeg在xcode 10无法真机编译运行, 自己编译的ff可以

### ISSUE THREAD

**Issue by NiuYangYang** [zhengwenming/WMPlayer#169]
真机无法运行, 模拟器可以

**Comment by NiuYangYang** [comment]
因为清晰度的问题, 已放弃这种使用方式, 谢谢

**Comment by Kingswhale** [comment]
Hi!
Please where you able to resolve this problem, if yes, how did you resolve it.
