### ISSUE TITLE
WNPlayer里面没有手势控制音量、进度的功能

### ISSUE THREAD

**Issue by superlu88** [zhengwenming/WMPlayer#181]
你好，WNPlayer里面没有手势控制音量、进度的功能，我看了一下代码WMPlayer里有这些功能。能不能完善一下WNPlayer，把WMPlayer有的功能都加到WNPlayer中去。
或者需要我自己进行添加，希望有一个回复，谢谢。

**Comment by zhengwenming** [comment]
您可以参考WMPlayer里面的代码，添加这些手势到WNPlayer里面，我没有那么快更新，所以如果是急着用，请自行添加
