### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by goodcyg** [zhengwenming/WMPlayer#185]
能否将wnplayer和wnplayer接口统一到一个xxplayer，通过一个属性设置，我就可以自由切换他们。这样不是更好用？wnplayer和wnplayer干都是同一事，只是他们内部用的编解码和渲染不同而已？

**Comment by zhengwenming** [comment]
首先，谢谢开发者对WMPlayer库的建议。下面我谈一下自己的思路
1、我是特意的把他们分开的，没有考虑全部都柔和到一起，这样开发者的选择性就会大大加强。如果喜欢全封装的一个类，可以推荐SGPlayer，作者把所有的情况都封装进去了，使用者必须全部加入SGPlayer的类文件。我把这两个组件完全解耦，独立开来了。一个是自行车、一个是坦克车，虽然都能干一件事，但是各有所长各有缩短。
2、开发者如果仅仅为了播放一个URL，而且是mp4的，很单一的功能，就是播放格式单一的视频资源，就用WMPlayer即可，无需加入FFmpeg的库，加入只会增加ipa的大小。
3、如果开发者需要播放更多格式的视频，还要播放RTMP、RTSP格式的，那就必须用WNPlayer

总之我的这种设计看上去显得散乱，无章，无规律。但是全是从使用者的角度来想的，使用者的可选择性强。使用者多，大家各自去使用适合自己的库就好了，希望大家理解。

**Comment by goodcyg** [comment]
其实两个统一一套接口和用户的使用，不矛盾。用宏编译就可以解决。用其一打开一个宏，用其二打开两个宏。使用也很方便。就像SGplayer的设计。这只是设计上的个人建议。

**Comment by zhengwenming** [comment]
有些人不想引入ffmpeg怎么办？他们担心ffmpeg太重，会加大ipa的体积

**Comment by goodcyg** [comment]
不用ffmpeg，次宏编译开关关闭。用了ijk，为啥还要用你的这个？

**Comment by goodcyg** [comment]
我只是觉得技术上完全可以达到要求。小建议✍️。
