### ISSUE TITLE
RTMP url is not working

### ISSUE THREAD

**Issue by iamvijay7** [zhengwenming/WMPlayer#186]
I am trying to play RTMP url but it gives me server error!

WMPlayerModel *playerModel = [WMPlayerModel new];
    playerModel.videoURL = [NSURL URLWithString:@"rtmp://184.72.239.149/vod/BigBuckBunny_115k.mov"];
    WMPlayer * wmPlayer = [[WMPlayer alloc]initPlayerModel:playerModel];
    [self.view addSubview:wmPlayer];
    [wmPlayer mas_makeConstraints:^(MASConstraintMaker *make) {
        make.leading.trailing.top.equalTo(self.view);
        make.height.mas_equalTo(wmPlayer.mas_width).multipliedBy(9.0/16);
    }];
    [wmPlayer play];

Can you help should i change any setting?

**Comment by zhengwenming** [comment]
Please use the WNPlayer component。The example code is in WNPlayerDetailViewController.m file

**Comment by iamvijay7** [comment]
Ok but when i try to run demo game getting 'libavformat/avformat.h' file not found error? How to solve this issue. There is no detail about WNPlayer much.

**Comment by iamvijay7** [comment]
> Please use the WNPlayer component。The example code is in WNPlayerDetailViewController.m file

Ok but when i try to run demo game getting 'libavformat/avformat.h' file not found error? How to solve this issue. There is no detail about WNPlayer much.
