### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by WelkinDev** [zhengwenming/WMPlayer#187]
在 WNPlayerDetailViewController.m 中，设置self.wnPlayer.urlString = @"rtsp://xxx";
运行后内存不断增长，直至Message from debugger: Terminated due to memory issue
求解，感谢

**Comment by zhengwenming** [comment]
我用iPhone XR测试的，链接地址：rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov
CPU：稳定在10%左右，偶尔会到18%
Memory：稳定在57.8MB
并没有不断的增长，因为测试了10分钟左右，没发现异常
请把您的测试地址和手机型号发给我，谢谢。

**Comment by WelkinDev** [comment]
用的iPhone7，链接地址是：rtsp://10.1.8.140/ch1

**Comment by zhengwenming** [comment]
你的是局域网链接，我这边播放不了，没办法测试。加我微信解决吧，18824905363

**Comment by WelkinDev** [comment]
是链接问题引起的，非常感谢作者的耐心帮助 👍
