### ISSUE TITLE
关于wnplayer的播放cpu占有率过高的问题

### ISSUE THREAD

**Issue by JonKerr-China** [zhengwenming/WMPlayer#188]
请问有什么办法可以优化wnplayer播放的时候cpu使用吗？

**Comment by zhengwenming** [comment]
Vulkan了解一下。跨平台、兼容性强、效率高。
Vulkan并计划提供高性能和低CPU管理负担（overhead），这也是Direct3D12和AMD的Mantle的目标。
同 OpenGL® 一样，Vulkan™ 也由 Khronos 集团开发。它是 AMD Mantle 的后续版本，继承了前者强大的低开销架构，使软件开发人员能够全面获取 Radeon™ GPU 与多核 CPU 的性能、效率和功能。

**Comment by JonKerr-China** [comment]
谢谢，另外我想请教下，我用WMPlayer，在播放M3U8视频文件，调整进度的时候，播放器的时间和画面是对不上的，只有WNPlayer才可以，请问是为什么？可以解决吗？

**Comment by zhengwenming** [comment]
WMPlayer内部是封装的苹果的AVPlayer，画音不同步是苹果没处理好吧，这个暂时解决不了，可能其他的播放器只要是封装AVPlayer的都存在这个问题。
WNPlayer是封装的ffmpeg，自己解码现实的，中间是处理了音频数据和视频数据的同步问题，网上有很多资源介绍音频和视频的同步问题的
普遍做法就三个：
1、依照音频的时间线为标准，不去管图像显示的对不对的上
2、依照视频的时间线为标准，不去管声音的播放对不对的上
3、音频和视频的时间点来回校对，不停的校对，这样大概就能保证同步，至少人眼和人耳是感觉同步了

**Comment by JonKerr-China** [comment]
谢谢！感谢你的回答！学习了！
