### ISSUE TITLE
'libavformat/avformat.h' file not found

### ISSUE THREAD

**Issue by hrscy** [zhengwenming/WMPlayer#189]
将 WMPlayer 文件夹拖到我自己的项目中，按照 readme 中配置之后，进行编译，WNPlayerDecoder.m 文件报错 'libavformat/avformat.h' file not found。
请问这是什么原因？
![image](https://user-images.githubusercontent.com/16634163/58741049-99d61780-8447-11e9-956f-010263852e99.png)

**Comment by gaoyinhui** [comment]
我也遇到了

**Comment by ChrisRockC** [comment]
同样的问题，在真机上运行就没有这样的bug了
