### ISSUE TITLE
播放非本地的视频时会出现卡顿,卡顿时播放按钮没有改变状态

### ISSUE THREAD

**Issue by MJHee** [zhengwenming/WMPlayer#19]

**Comment by zhengwenming** [comment]
1、首先，很感谢你的支持。

2、播放器目前还没加缓冲loading的等待⌛️，所以网络不好的时候，buffer缓冲区已经无data播放，造成卡住的现象。按钮这个时候不变化状态。

3、接下来我会加入播放进度显示缓冲功能，以及缓冲loading的等待⌛️。
