### ISSUE TITLE
wmPlayer不支持本地rmvb格式的视频播放？

### ISSUE THREAD

**Issue by Kangqj** [zhengwenming/WMPlayer#191]
wmPlayer不支持本地rmvb格式的视频播放吗？
我看readme里介绍的是支持的呀，怎么使用中不支持？

错误提示：
2019-06-04 10:26:32.147863+0800 SecureBox_debug[15136:2558461] 视频加载失败===Error Domain=NSCocoaErrorDomain Code=257 "未能打开该文件，因为您没有查看它的权限。" UserInfo={NSUnderlyingError=0x2818ffba0 {Error Domain=NSOSStatusErrorDomain Code=-12203 "(null)"}}

**Comment by zhengwenming** [comment]
支持。
请用WNPlayer（万能播放器）组件播放

**Comment by Kangqj** [comment]
WNPlayer 是不是比wmPlayer支持的格式多一点？

WNPlayer可以完全替换wmPlayer吗？

**Comment by Kangqj** [comment]
> 支持。
> 请用WNPlayer（万能播放器）组件播放

我测试发现使用wnplay连续播放几个rmvb视频后，内存占用很大，一会儿就crash了。
能优化下吗？

**Comment by yuanweiphone** [comment]
作者，你好
播放本地视频提示The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x600003ca97d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
但是本地是存在文件的，这是什么原因呢？

**Comment by Kangqj** [comment]
> 作者，你好
> 播放本地视频提示The requested URL was not found on this server." UserInfo={NSLocalizedDescription=The requested URL was not found on this server., NSUnderlyingError=0x600003ca97d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
> 但是本地是存在文件的，这是什么原因呢？

本地文件url路径用 [NSURL **fileURLWithPath**:self.videoPath] 试试看

**Comment by zhengwenming** [comment]
WNPlayer 是不是比wmPlayer支持的格式多一点？

WNPlayer可以完全替换wmPlayer吗？

1、WNPlayer肯定比WMPlayer支持的格式多，因为是基于ffmpeg的，WNPlayer是万能播放器的意思。
2、WNPlayer完全可以替代或者说替换WMPlayer，两者设计完全解耦，可以任意使用其中一个。
