### ISSUE TITLE
请问ffmpeg的封装在什么地方？

### ISSUE THREAD

**Issue by MuZiLee** [zhengwenming/WMPlayer#193]
我看到源码就是封装了AVPlayer，并没有ffmpeg的内容呢？
请问一下ffmpeg 4.0的处理在哪里？

**Comment by zhengwenming** [comment]
在WNPlayer组件里面，不支持pod集成，可能你pod集成的WMPlayer。看一下我的demo就一目了然了，开源的，代码都可以看到。
