### ISSUE TITLE
支持h265的视频吗

### ISSUE THREAD

**Issue by YYHNobug** [zhengwenming/WMPlayer#196]
支持h265的视频吗

**Comment by zhengwenming** [comment]
支持，如果播放失败，请提供url，谢谢

**Comment by YYHNobug** [comment]
测试了几个h265不能播，
1、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/185.132.176.172:8278/1323e5a733/playlist.m3u8

2、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/50.7.161.82:8278/aec2bef9c4/playlist.m3u8

3、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/185.180.221.194:8278/a4320e9d8b/playlist.m3u8

**Comment by YYHNobug** [comment]
有的可以播放十几秒就报错了
1、http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/4e9bfbe39a/playlist.m3u8
2、http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8

报错如下：

Input #0, hls,applehttp, from 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8':
  Duration: N/A, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: hevc ([36][0][0][0] / 0x0024), none, 90k tbn
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 0 channels
    Metadata:
      variant_bitrate : 0
[http @ 0x1050f2200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/./19070102594575.ts' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
[http @ 0x1029b3200] Opening 'http://yflive2.lemmovie.com/cdn/50.7.161.82:8278/ae9a42c7da/playlist.m3u8' for reading
2019-07-02 14:58:50.272387+0800 PlayerDemo[82355:42042644] read frame error: End of file

**Comment by YYHNobug** [comment]
您好，WNPlayer支持播放加密的m3u8吗，后台把每个ts的地址都进行了加密（自定义的加密算法），这种场景用WNPlayer能实现吗？我用AVPlayer已经实现了解密播放，但AV不支持H265。。

**Comment by jeff-kl** [comment]
> 测试了几个h265不能播，
> 1、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/185.132.176.172:8278/1323e5a733/playlist.m3u8
> 
> 2、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/50.7.161.82:8278/aec2bef9c4/playlist.m3u8
> 
> 3、http://yflive2.lemmovie.com/cdn/52.221.210.243/cdn/185.180.221.194:8278/a4320e9d8b/playlist.m3u8

你好, 请问这个的列表可以发来看看吗? qq 1493810639
