### ISSUE TITLE
上架失败问题

### ISSUE THREAD

**Issue by zhangzuoren** [zhengwenming/WMPlayer#199]
打包上架时，提示：Non-public API usage - The app references non-public symbols in XXX: _locale_charset.
由于导入了libiconv.tbd,在WNPlayer中使用了此私有API，导致项目无法上架。

**Comment by zhengwenming** [comment]
是不是有导入环信2.0SDK。
这个文件是iOS提供的Framework，是在使用环信2.x时官方文档要求导入的，里面有_locale_charset
把这个文件移除后编译+运行 没有任何问题… 
然后继续打包上传…但是还是回执邮件调用了私有api _locale_charset

因为其他第三方库都不需要导入libiconv.tbd，只有环信2.x要求导入，猜想是环信2.x的源代码引用了Apple的私有api，将环信2.x从工程中移除后再打包上传…成功了！没有回执邮件，构建版本中也出现了

之后咨询了环信的技术客服，导入最新的环信3.x后，问题完美解决…再也没收到调用私有api的回执邮件… 
在此得感谢一下环信的技术客服，那哥们太负责了…在QQ上陪我解决这个问题到深夜2 3点
--------------------- 
版权声明：本文为CSDN博主「Raining_XZY」的原创文章，遵循CC 4.0 by-sa版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/Raining_XZY/article/details/51280902
