### ISSUE TITLE
播放完 或 销毁wmplayer的时候为什么没有调用dealloc方法？

### ISSUE THREAD

**Issue by jimckylin** [zhengwenming/WMPlayer#2]
如题所述

**Comment by zhengwenming** [comment]
内存泄漏问题已经解决，谢谢你的支持。
下面具体原因：
原因是定时器没有释放，当你用  self.autoDismissTimer = [NSTimer timerWithTimeInterval:5.0 target:self selector:@selector(autoDismissBottomView:) userInfo:nil repeats:YES];这句代码的时候，target：self会让WMPlayer的retain count加1，如果不把定时器invalidate（释放），那么WMPlayer不会调用dealloc方法，资源得不到回收。

**Comment by jimckylin** [comment]
不客气~， 最近在做视频方面的应用，想用这个控件，但是没有边播边下的功能，能否添加这个功能，希望这个控件能越来越完善。

**Comment by zhengwenming** [comment]
以后会考虑添加边下载边播放的功能，目前太忙没时间更新，望见谅。
