### ISSUE TITLE
下载demo后出现找不到google-vr.mp4和avi.avi?

### ISSUE THREAD

**Issue by Lianghuajian** [zhengwenming/WMPlayer#201]

**Comment by zhengwenming** [comment]
在Supporting Files里面，找到他删掉即可

**Comment by Lianghuajian** [comment]
对你可以修复一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 文明 <notifications@github.com>
发送时间: 2019年8月23日 10:06
收件人: zhengwenming/WMPlayer <WMPlayer@noreply.github.com>
抄送: lianghuajian <624935495@qq.com>, Author <author@noreply.github.com>
主题: 回复：[zhengwenming/WMPlayer] 下载demo后出现找不到google-vr.mp4和avi.avi? (#201)




在Supporting Files里面，找到他删掉即可
