### ISSUE TITLE
lavfilter 这个库是什么，下载后运行会报错，显示找不到

### ISSUE THREAD

**Issue by sunJackie** [zhengwenming/WMPlayer#206]
lavfilter 这个库是什么，下载后运行会报错，显示找不到

**Comment by ligangliang** [comment]
这个需要额外导入FFpage 里面的.a 文件，GitHub ，上百度网盘下载即可




------------------ 原始邮件 ------------------
发件人: "sunJackie"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 中午11:11
收件人: "zhengwenming/WMPlayer"<WMPlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zhengwenming/WMPlayer] lavfilter 这个库是什么，下载后运行会报错，显示找不到 (#206)




lavfilter 这个库是什么，下载后运行会报错，显示找不到
