### ISSUE TITLE
干掉Masonry

### ISSUE THREAD

**Issue by CharlinFeng** [zhengwenming/WMPlayer#21]
1.干掉Masonry
2.初始化不需要url（支持xib）

**Comment by zhengwenming** [comment]
冯哥啊，幸会幸会，谢谢前辈的意见。
1、Masonry仅仅是为了布局UI用的，的缺是要干掉（有点多余），变成轻量级的一个UIView子类。
2、初始化可以不需要URL，直接setURLString就可以了，这个API会更新添加上去。xib到时候也会支持的。

再次感谢冯哥的好建议。
