### ISSUE TITLE
Demo提供的类,不能触发视频结束的通知

### ISSUE THREAD

**Issue by LipYoung** [zhengwenming/WMPlayer#22]
WMPlayerFinishedPlayNotification 这个通知无法触发

**Comment by LipYoung** [comment]
[self.wmPlayer setURLString:urlString];
    [self.wmPlayer play];
    [self.maskView addSubview:self.wmPlayer];

**Comment by zhengwenming** [comment]
你好，首先很感谢您使用WMPlayer。
这个bug是我更新改版的时候忘记添加一句代码导致的，由于还没改办完成，所以我还没提交代码，你只需要进WMPlayer.m文件中，修改一下源代码就可以了。（实际上就是用下面的方法覆盖一下你项目中的那个方法代码）。我会尽快改版WMPlayer2.0，尽快提交，给您带来的不便还请原谅。
- (void)moviePlayDidEnd:(NSNotification *)notification {
    __weak typeof(self) weakSelf = self;
    [[NSNotificationCenter defaultCenter] postNotificationName:WMPlayerFinishedPlayNotification object:nil];//少加了这句代码，加上就OK了。
    [weakSelf.player seekToTime:kCMTimeZero completionHandler:^(BOOL finished) {
        [weakSelf.progressSlider setValue:0.0 animated:YES];
        weakSelf.playOrPauseBtn.selected = NO;
    }];
}

**Comment by LipYoung** [comment]
谢谢,我马上去试试
