### ISSUE TITLE
打上了 All Exceptions 后老是会断点断在main和汇编中。为什么？请指教

### ISSUE THREAD

**Issue by zhangchioulin** [zhengwenming/WMPlayer#24]
就是播放视频前会跳到一段汇编中
`
libc++abi.dylib`__cxa_throw:
->  0x113cb0c6b <+0>:   pushq  %rbp
    0x113cb0c6c <+1>:   movq   %rsp, %rbp
    0x113cb0c6f <+4>:   pushq  %r15
    0x113cb0c71 <+6>:   pushq  %r14
    0x113cb0c73 <+8>:   pushq  %r12
`
main语句也会打上断点，而且wmplayer的代理没有回调
但程序能继续运行

**Comment by zhengwenming** [comment]
首先，很感谢你的使用和支持。
集成过程中有bug或者问题，可以直接发小demo给我邮箱，740747055@qq.com

**Comment by zhangchioulin** [comment]
谢谢
