### ISSUE TITLE
在播放视频的时候发现,播放内容变形了,该设置哪个属性?

### ISSUE THREAD

**Issue by zhangchioulin** [zhengwenming/WMPlayer#26]
如题,麻烦您告知下,谢谢!

**Comment by zhengwenming** [comment]
/**
 *  重写URLString的setter方法，处理自己的逻辑，
 */
- (void)setURLString:(NSString *)URLString{
    _URLString = URLString;
    //设置player的参数
    self.currentItem = [AVPlayerItem playerItemWithURL:[NSURL URLWithString:URLString]];

    self.player = [AVPlayer playerWithPlayerItem:_currentItem];
    self.player.usesExternalPlaybackWhileExternalScreenIsActive=YES;
    //AVPlayerLayer
    self.playerLayer = [AVPlayerLayer playerLayerWithPlayer:self.player];
    self.playerLayer.frame = self.layer.bounds;
    //WMPlayer视频的默认填充模式，AVLayerVideoGravityResizeAspect
    self.playerLayer.videoGravity = AVLayerVideoGravityResize;
    [self.layer insertSublayer:_playerLayer atIndex:0];
    self.state = WMPlayerStateBuffering;
    if (self.closeBtnStyle==CloseBtnStylePop) {
        [_closeBtn setImage:[UIImage imageNamed:WMPlayerSrcName(@"play_back.png")] ?: [UIImage imageNamed:WMPlayerFrameworkSrcName(@"play_back.png")] forState:UIControlStateNormal];
        [_closeBtn setImage:[UIImage imageNamed:WMPlayerSrcName(@"play_back.png")] ?: [UIImage imageNamed:WMPlayerFrameworkSrcName(@"play_back.png")] forState:UIControlStateSelected];
        
    }else{
        [_closeBtn setImage:[UIImage imageNamed:WMPlayerSrcName(@"close")] ?: [UIImage imageNamed:WMPlayerFrameworkSrcName(@"close")] forState:UIControlStateNormal];
        [_closeBtn setImage:[UIImage imageNamed:WMPlayerSrcName(@"close")] ?: [UIImage imageNamed:WMPlayerFrameworkSrcName(@"close")] forState:UIControlStateSelected];
    }
}



改一下这个枚举值就可以了
 //WMPlayer视频的默认填充模式，AVLayerVideoGravityResizeAspect
    self.playerLayer.videoGravity = AVLayerVideoGravityResize;
