### ISSUE TITLE
返回崩溃问题

### ISSUE THREAD

**Issue by liao5836** [zhengwenming/WMPlayer#27]
dealloc释放self.currentItem 遇到崩溃现象  ，原因是重写currentItem set方法时判断使用_currentItem，_currentItem未清空.

**Comment by zhengwenming** [comment]
你是解决了呢？还是没解决？还是你解决了我项目中的bug？还是？抑或。。。。
请描述清楚一点，谢谢

**Comment by liao5836** [comment]
问题我是解决了，我只是想你反馈这个使用问题

**Comment by zhengwenming** [comment]
哦，谢谢你。能否把关键代码发一下，防止其他使用者的APP崩溃。

**Comment by zhengwenming** [comment]
bug已经解决，请更新最新的demo
