### ISSUE TITLE
如果播放一个有问题的链接，返回后啥也不能操作了，整个界面，整个App都不能操作了。

### ISSUE THREAD

**Issue by mrhyh** [zhengwenming/WMPlayer#28]
我测试用的这个视频地址是：    [self.wmPlayer setURLString:@"http://192.168.0.128:81/easyframe/ubirth/riskfile/182/1ae5f8f4-6a3a-458f-9d86-09c070bb3455.mp4"];

我是在这个类里测试的TestViewController

**Comment by mrhyh** [comment]
谢谢帮助解决！

**Comment by zhengwenming** [comment]
不客气，有其他问题，都可以提issue
