### ISSUE TITLE
拖拽视频进度条的时候不平滑，有拖不动的感觉

### ISSUE THREAD

**Issue by hnluowen** [zhengwenming/WMPlayer#3]
看了代码，作者好像只在UIControlEventTouchUpInside的时候做了事件处理，作者可以考虑优化下这个问题

**Comment by zhengwenming** [comment]
首先感谢你们的宝贵意见和支持。
关于拖曳不平滑的问题，我会认真优化，WMPlayer的确存在这个问题，持续关注WMPlayer，谢谢！您的宝贵意见是WMPlayer进步的动力。

**Comment by shanchaojie** [comment]
@hnluowen 我已经解决了这个问题,请看第十三条评论与附件

**Comment by zhengwenming** [comment]
代码已经更新，bug已经解决，谢谢大家的支持和使用。
