### ISSUE TITLE
一直播放失败，视频加载失败

### ISSUE THREAD

**Issue by DeftMKJ** [zhengwenming/WMPlayer#30]
视频加载失败===Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x7f82ca855a40 {Error Domain=NSOSStatusErrorDomain Code=-101 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-101), NSLocalizedDescription=The operation could not be completed}

希望能帮下我，急

**Comment by zhengwenming** [comment]
把视频的URL贴出来。

**Comment by zhengwenming** [comment]
把视频的URL贴出来。

**Comment by zhengwenming** [comment]
把视频的URL贴出来。

**Comment by zhengwenming** [comment]
把视频的URL贴出来。

**Comment by DeftMKJ** [comment]
昨天是所有的URL都加载失败，但是直接拿出来放网页就可以，KVO监听到的全是failed，我去StackOverFlow找了一圈都找懵逼了，无解，早上来打开又好了，这是什么鬼。。。。。。

**Comment by angBiu** [comment]
会出现这种情况  点进去详情视频加载出来了  然后返回 在进去 在返回 在进去 这样重复多次后就会出现 所有的avplayer无论加载什么url都加载不出来了 状态都是AVPlayerStatusUnknown 再AVPlayerStatusFailed

**Comment by angBiu** [comment]
发现这个时候 dealloc是不走的了

**Comment by DeftMKJ** [comment]
我都没重复进去，数据都是最新刷出来的，直接点击播放，一直跑AVPlayerStatusFailed的监听事件里面去，根本无法加载视频，然后今天莫名其妙可以了，我只想知道为什么一直failed，无论什么URL都failed，这种报错各大论坛都找了，无解，有个大神说layer问题，我还是太水，搞不懂为什么

**Comment by zhengwenming** [comment]
这个问题就是因为你们没有释放一些资源，导致内存泄漏，这样说可能很不清晰。那么具体来说一说，比如，你们用block的时候没注意用weakSelf，造成了VC不走dealloc，那么以后就别想加载视频了，所有的视频都是加载失败的。当然这是一个最主要的原因，可能还有一些其他的原因导致内存泄漏，不走dealloc的情况。视频播放器本事没有问题的，可以放心使用，使用过程中，遇到播放器本事的问题可以直接联系我。

最后总结，做项目的时候，虽然是ARC了，但是一定要代码规范，改释放的资源一定要释放，dealloc一定，是一定，是100%的确定要走的。

**Comment by DeftMKJ** [comment]
文明哥，但是我只是单纯跑你的Demo出现的啊，我自己集成的项目没问题哦......暂时没问题了，以后还遇到就按你的思路找找bug

**Comment by angBiu** [comment]
好的 谢谢哈～ 检查检查
