### ISSUE TITLE
不支持wmv格式

### ISSUE THREAD

**Issue by mrhyh** [zhengwenming/WMPlayer#32]

**Comment by zhengwenming** [comment]
谢谢你的使用。
对的，因为是封装的AVPlayer，AVPlayer支持的都支持，AVPlayer不支持的也都同样不支持。您可以考虑用ijkPlayer。
标题上面如是说：
WMPlayer视频播放器，AVPlayer的封装，继承UIView，想怎么玩就怎么玩。支持播放mp4、m3u8、3gp、mov，网络和本地视频同时支持。全屏和小屏播放同时支持
