### ISSUE TITLE
您好，怎么播放4K分辨率的视频资源？

### ISSUE THREAD

**Issue by 13027776717** [zhengwenming/WMPlayer#34]
4K以下的都能完美播放，但是4K的怎么播放，求大神赐教

**Comment by zhengwenming** [comment]
给你看一个接口数据，高清和标清是接口控制的。标清要给标清的对应的URL，高清要给高清对应的URL。
[
                             {
                             "height":480,
                             "width":854,
                             "name":"标清",
                             "type":"normal",
                             "url":"http://baobab.wdjcdn.com/1457546796853_5976_854x480.mp4"
                             },
                             {
                             "height":720,
                             "width":1280,
                             "name":"高清",
                             "type":"high",
                             "url":"http://baobab.wdjcdn.com/14573563182394.mp4"
                             }
                             ]

**Comment by 13027776717** [comment]
大神你好，麻烦你百忙中抽出时间来查看我的问题。可能是我没写清楚，我现在播放不出来的分辨率是4096*2048，

**Comment by zhengwenming** [comment]
请你把视频的URL发给我，或者是你写一个小demo，发给我邮箱，740747055@qq.com
