### ISSUE TITLE
关于state的问题

### ISSUE THREAD

**Issue by Guicai-Li** [zhengwenming/WMPlayer#35]
typedef NS_ENUM(NSInteger, WMPlayerState) {
    WMPlayerStateFailed,        // 播放失败
    WMPlayerStateBuffering,     // 缓冲中
    WMPlayerStatusReadyToPlay,  //将要播放
    WMPlayerStatePlaying,       // 播放中
    WMPlayerStateStopped,        //暂停播放
    WMPlayerStateFinished       //播放完毕
};
在使用过程中，并不是很严格。
例如，在wmPlayer.state readyToPlay时，而实际上已经播放。
而且，在使用pause时，暂停时状态变化诡异

**Comment by zhengwenming** [comment]
谢谢你的bug反馈，如果方便的话，可以发个demo到我邮箱 740747055@qq.com
我会尽快测试修复bug的。
