### ISSUE TITLE
想问下，修改self.wmPlayer.frame的同时修改self.wmPlayer.playerLayer.frame,会有问题

### ISSUE THREAD

**Issue by joshua-hua** [zhengwenming/WMPlayer#37]
想问下，修改self.wmPlayer.frame的同时修改self.wmPlayer.playerLayer.frame,
会优先修改self.wmPlayer.playerLayer.frame，导致视频看起来出框了，想问下self.wmPlayer.playerLayer.frame的修改是不是自带了动画？可是找了下并没有见到有动画。

if (newOffset.y > 20) {
            CGRect frame = self.frame;
        if(frame.size.width>120){
            frame.size.height = frame.size.height - newOffset.y;

```
    }
        if(frame.size.height<120){
        frame.size.height = 120;

    }
        self.wmPlayer.frame = frame;
        self.wmPlayer.playerLayer.frame = frame;
        self.wmPlayer.bottomView.frame = CGRectMake(0, self.wmPlayer.frame.size.height-40, SCREEN_WIDTH, 40);
        self.scrollView.frame = CGRectMake(0, 120, SCREEN_WIDTH, SCREEN_HEIGHT-120);
}else{
        CGRect frame = self.frame;
        if (frame.size.height<195) {
            frame.size.height = frame.size.height + newOffset.y;
        }
        if (frame.size.height>195) {
            frame.size.height = 195;
        }

        self.wmPlayer.frame = frame;
        self.wmPlayer.playerLayer.frame = frame;
        self.wmPlayer.bottomView.frame = CGRectMake(0, self.wmPlayer.frame.size.height-40, SCREEN_WIDTH, 40);
        self.scrollView.frame = CGRectMake(0, 195, SCREEN_WIDTH, SCREEN_HEIGHT-195);
}
```

我是这样写的。希望能指导下。

**Comment by zhengwenming** [comment]
你如果想改变视频内容的填充模式，你可以修改一下这个宏（系统宏）。
//WMPlayer视频的默认填充模式，AVLayerVideoGravityResizeAspect
    self.playerLayer.videoGravity = AVLayerVideoGravityResize;

另外self.wmPlayer.frame仅仅是视频播放器容器UIView的frame，就是单单是一个UIView。这个里面放置的是视频播放器。
self.wmPlayer.playerLayer.frame这个是直接修改了视频内容的frame，视频的显示是用layer显示的，在layer层上，view上是无法渲染这个视频的，所以，你修改的是layer的frame，是可见视频的大小。
