### ISSUE TITLE
这个masonry的问题可否修复一下 每次播放都提示这个

### ISSUE THREAD

**Issue by LiuYuHangNB** [zhengwenming/WMPlayer#39]
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x7fad86842790 UIProgressView:0x7fad82dee750.left == UISlider:0x7fad8698f0d0.left>",
    "<MASLayoutConstraint:0x7fad868433a0 UIProgressView:0x7fad82dee750.right == UISlider:0x7fad8698f0d0.right>",
    "<MASLayoutConstraint:0x7fad86843400 UIProgressView:0x7fad82dee750.centerX == UISlider:0x7fad8698f0d0.centerX + 0.7>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7fad86843400 UIProgressView:0x7fad82dee750.centerX == UISlider:0x7fad8698f0d0.centerX + 0.7>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by zhengwenming** [comment]
谢谢你的反馈意见。
autoLayout的约束冲突⚠️警告已经修复。谢谢您的使用，请更新WMPlayer，谢谢。
