### ISSUE TITLE
手势操作支持播放进度，亮度调整

### ISSUE THREAD

**Issue by ji3g4m6zo6** [zhengwenming/WMPlayer#4]
谢谢您这么优秀的播放器

请问未来手势操作会支持播放进度与亮度调整吗？

谢谢

**Comment by zhengwenming** [comment]
谢谢您的使用，同时也感谢你的支持和建议。
我会采纳您的建议，很多视频播放器都有这些功能，WMPlayer当然也会有这些最基本的功能。
手势快进和手势调节屏幕亮度这两个功能我会在后续添加上去，请您关注WMPlayer，谢谢。
