### ISSUE TITLE
真机上没有画面是怎么回事

### ISSUE THREAD

**Issue by HotSummerS** [zhengwenming/WMPlayer#40]
我是直接复制的你demo里的DetailViewController文件里的创建方法，但是真机上就是没有画面

**Comment by HotSummerS** [comment]
作者辛苦了，我用的真机是5S，系统是9.3的系统，demo是刚从你这里下载的，约束没问题了，可是现在真机播放没有画面，我同事iphone6 也是没有画面只有声音

**Comment by zhengwenming** [comment]
所有的URL资源都是没画面的吗？你试试多换几个试试。
你可以直接用我的demo测试。看看是否有画面和声音

**Comment by HotSummerS** [comment]
用你的demo试也没有画面，只有声音http://114.55.175.11:80/resources/video/2016/0802/1470147878958662.mp4

这个是链接，在安卓的机器上可以播放

**Comment by zhengwenming** [comment]
如果解决不了，你把URL贴出来，然后说明你的iOS版本，iPhone几。然后我测试一下。

**Comment by liyunhe** [comment]
我也遇到这个问题  请问 楼主  如何解决的
