### ISSUE TITLE
不能播放本地视频

### ISSUE THREAD

**Issue by purple-T** [zhengwenming/WMPlayer#41]
```
   wmPlayer = [[WMPlayer alloc]initWithFrame:videoRect];
    wmPlayer.delegate = self;
    wmPlayer.closeBtnStyle = CloseBtnStyleClose;
    wmPlayer.URLString = [[NSBundle mainBundle] pathForResource:@"失恋33天" ofType:@"mp4"];
    [self.view addSubview:wmPlayer];
   [wmPlayer play];
```

当播放本地视频时，指示器一直显示，而且不能播放

**Comment by zhengwenming** [comment]
NSURL *URL = [NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"4k" ofType:@"mp4"]];
    NSString *urlstring = [URL absoluteString];
    [self.wmPlayer setURLString:urlstring];

**Comment by purple-T** [comment]
可以了，谢谢！

**Comment by zhengwenming** [comment]
本地文件的URL对应的是一个file，一个文件，所以加载本地文件的URL用这个fileURLWithPath。
HTTP的URL又是一种类型，不要混淆了，要分清楚。

**Comment by purple-T** [comment]
好的，受教了！非常感谢

**Comment by mzying2013** [comment]
**/private/var/mobile/Containers/Data/Application/DD7D531B-212B-49BD-8E9A-C0A66D70A4DD/tmp/video_6BEC1B2F-56D4-4DC8-BC43-43112FEFC41C.mp4**
我用摄像头拍摄的一段视频，放在tmp目录下，我使用了上面fileURLWithPath的方式，也是提示播放失败：
> 视频加载失败===Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server."

**Comment by zhengwenming** [comment]
有demo吗？或者代码贴给我，我只要能测试就可以，我测试不了的话，也是白说。
其实播放本地的视频也是先获取path路径，然后转NSURL，我的WMPlayer要求传NSString，所以你拿到的NSURL要转成NSString，WMPlayer拿到这个NSString就会再次转成NSURL，最好转成AVPlayerItem播放

**Comment by mzying2013** [comment]
https://coding.net/u/mzying2015/p/TestCaptureAndPlay/git

点击Video List的某行，就是播放。谢谢你能回复。

**Comment by mzying2013** [comment]
又突然可以了，不知道为什么。还是感谢你的回复。

下面这种静音是没效果吗？
self.player.muted = YES;
[self play];

**Comment by mzying2013** [comment]
[self play];
self.player.muted = YES;

.muted写在play方法之后，应为player对象是在这之后实例化的。

**Comment by mzying2013** [comment]
知道上面那个问题怎么回事了。tmp目录，如果非debug模式，视频文件一直存在。但是如果第二次debug调试，path路径就找不到对应的文件了。不知道为什么？好奇怪。

**Comment by mzying2013** [comment]
又要来打扰了，总算解决了。
> APP每次调试启动的时候，TMP目录都会改变。所以需要动态获取TMP目录路径。


`@implementation NSString (TempPath)

-(NSString *)videoPath{
    NSString * tmp = NSTemporaryDirectory();
    NSString * fileName = [self lastPathComponent];
    return [tmp stringByAppendingString:fileName];
}

@end`

**Comment by zhengwenming** [comment]
解决了就好，那句代码是静音🔇了。你注释掉吧，可能会影响你测试。
self.player.muted = YES;
