### ISSUE TITLE
关于重连时间的问题

### ISSUE THREAD

**Issue by GorCat** [zhengwenming/WMPlayer#43]
(｡･∀･)ﾉﾞ嗨，文明大神，我用了你的 wmPlayer ，非常好用，但是它抛出 “视频加载失败” 的时间太长了，我们希望 wmPlayer 能在15s 中重连 3 次左右，超过 15s 还没连不上就判断为加载失败，我想可以直接退了就好，但是老大表示，我不能这么残暴的对待代码，所以，我们想来征求一下你的意见 ~

**Comment by zhengwenming** [comment]
这个视频加载失败的原因可能有很多，比如
1、网络原因
2、视频资源的原因（资源不可用）
3、视频资源的初始化过程中出了点小问题，偶尔发生，但是视频没问题，第二次可以正常播放
4、服务器的问题
您说的，加这个15s重连的逻辑，可以在源代码里面修改，其他的开发者一般不需要这个功能，所以只能你本人修改源代码了，具体的思路是，加一个NSTimer计时，15s后，停止播放，同时发出你自己的通知，方便您在vc中做其他的逻辑，比如直接退出这个页面pop，释放wmplayer

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
