### ISSUE TITLE
WMPlayer.m文件- (void)appDidEnterBackground:(NSNotification*)note

### ISSUE THREAD

**Issue by amazing-longdd** [zhengwenming/WMPlayer#44]
当视频播放中进入后台时 视频会继续播放 存在bug
逻辑问题 将if 和 else 中的内容交换一下可解决

**Comment by zhengwenming** [comment]
这个进入后台继续播放不是bug，是我故意这么做的，这个是一个功能点。
如果你想要进入后台播放（继续播放视频）这个功能就不用注释代码
如果你不需要进入后台播放，那么注释掉进入前台和进入后台的通知方法里面的方法就可以了。
PS：哔哩哔哩的APP是可以进入后台继续播放视频的。
