### ISSUE TITLE
网络视频正在加载的时候返回控制器 闪退

### ISSUE THREAD

**Issue by amazing-longdd** [zhengwenming/WMPlayer#48]
![image](https://cloud.githubusercontent.com/assets/11324430/19471070/5f1f25c6-9554-11e6-90c0-9a3ea4820b4c.png)
![image](https://cloud.githubusercontent.com/assets/11324430/19471077/6816bb94-9554-11e6-9e2a-7fb202d0afe3.png)

崩在了如图所示的地方。

**Comment by zhengwenming** [comment]
您好，感谢您使用WMPlayer。
1、首先，确定你是否调用了下面这个方法
/**
 *  释放WMPlayer
 */
-(void)releaseWMPlayer{
     //堵塞主线程
//    [wmPlayer.player.currentItem cancelPendingSeeks];
//    [wmPlayer.player.currentItem.asset cancelLoading];
    [wmPlayer pause];

    
    [wmPlayer removeFromSuperview];
    [wmPlayer.playerLayer removeFromSuperlayer];
    [wmPlayer.player replaceCurrentItemWithPlayerItem:nil];
    wmPlayer.player = nil;
    wmPlayer.currentItem = nil;
    //释放定时器，否侧不会调用WMPlayer中的dealloc方法
    [wmPlayer.autoDismissTimer invalidate];
    wmPlayer.autoDismissTimer = nil;
    
    
    wmPlayer.playOrPauseBtn = nil;
    wmPlayer.playerLayer = nil;
    wmPlayer = nil;
}

2、如果调用了releaseWMPlayer释放了employer对象，那么可以发您的demo（带有崩溃bug的）到我的邮箱，我帮你调试。注意：邮件中稍微描述一下操作步骤，需求之类的。740747055@qq.com

**Comment by amazing-longdd** [comment]
你好 打扰你了 。我并没有手动调用你上述的方法 。我也并没有发现有这个方法。
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <WMPlayer 0x7f96055736f0> for the key path "status" from <AVPlayerItem 0x6000002011f0> because it is not registered as an observer.'

这是奔溃日志 。麻烦你看一下 谢谢

**Comment by amazing-longdd** [comment]
viewWillDisappear里面调用resetWMPlayer 可以解决问题了 。虽然我不知道为什么

**Comment by zhengwenming** [comment]
kvo的问题，没有注册kvo监听，就去remove，那么就崩溃了。
Cannot remove an observer for the key path "status" from because it is not registered as an observer.'
意思就是你不能移除一个名字叫status的keypath，因为他没有被注册。
