### ISSUE TITLE
手势滑动返回，视频会出现卡顿

### ISSUE THREAD

**Issue by fakeros** [zhengwenming/WMPlayer#5]
你好，我最近也在做视频播放的项目，但是我发现进入播放详情页的时候，如果用手势滑动返回的话，视频就会卡顿，不知道你有好的解决方案不。

**Comment by zhengwenming** [comment]
你好，手势返回确实会引起页面卡顿不流畅，暂时还没好的解决方案，可能是继承UIView的影响。谢谢你的支持。

**Comment by zhengwenming** [comment]
请更新demo解决手势返回卡顿问题。

**Comment by angBiu** [comment]
@zhengwenming  嗨 请问这个的原因是什么呢
