### ISSUE TITLE
全屏时的一些建议

### ISSUE THREAD

**Issue by GCIOS** [zhengwenming/WMPlayer#52]
当点击全屏来到 toFullScreenWithInterfaceOrientation 方法时, 不用从新修改那么多控件的约束, 只需要在WMPlayer 内部初始化时, 添加一个(UIView *)containerView,  把所有的子控件放到它的上面, 以后全平时, 只修改containerView 的约束;

**Comment by zhengwenming** [comment]
恩，很感谢你的意见，你说的是对的，我这里处理的不好。
你说的优化方案是比较好的，我下一步会采取你的方案，放一个UIView视图统一管理这些子控件，这样代码就简洁了。

再次感谢你的优化建议。

**Comment by zhengwenming** [comment]
已经测试，不好使。
