### ISSUE TITLE
cell播放的时候，点击进入详情页，再进行全屏播放的时候，会出现两个播放界面

### ISSUE THREAD

**Issue by GITYanghengzhan** [zhengwenming/WMPlayer#56]

**Comment by zhengwenming** [comment]
正常的，WMPlayer不是单利，可以同时进行n个视频的播放。
demo中没处理同时播放n个视频的逻辑，所以你认为是bug。真正项目中，你要处理多个视频播放的逻辑处理，比如，第二个视频播放的时候，第一个视频不能全屏。例子而已，不一定是我说的这样。但是就是这么回事。
这是个demo不是项目，demo只是演示WMPlayer怎么使用，并不需要把所有的逻辑都处理了，毕竟对于每个开发者来说，代码是可以copy，可以参考的，逻辑几乎全部都不一样。
