### ISSUE TITLE
KVO 监听里面的AVPlayerStatus问题

### ISSUE THREAD

**Issue by xiaoyuAhaha** [zhengwenming/WMPlayer#57]
你监听的对象是AVPlayerItem，在KVO里面
‘AVPlayerStatus status = [[change objectForKey:NSKeyValueChangeNewKey] integerValue];’

AVPlayerStatus不应该是AVPlayerItemStatus吗

**Comment by zhengwenming** [comment]
恩，你说的是对的，应该是AVPlayerItemStatus，我这里写错了。
AVPlayerStatus和AVPlayerItemStatus都对应三种状态，所以两者通用，都是枚举，代表的值为0，1，2
你可以改过来，我以后会更新过来的，但是不影响WMPlayer的使用。没bug，没毛病。
谢谢您的提醒。。
