### ISSUE TITLE
我这有一个m3u8  地址播到一半就卡住了 没有任何状态码日志

### ISSUE THREAD

**Issue by kule123** [zhengwenming/WMPlayer#59]
http://wscdn.alhls.xiaoka.tv/20161115/57c/da6/OM7VL1SYM2L37pF3/index.m3u8  就是地址播放器上播不了 但是在VLC上面可以正常播放

**Comment by zhengwenming** [comment]
我测试了，从0秒开始播放确实会暂停，播放m3u8是有点问题，可能是内存上的问题，也可能是视频本身的问题，你直接跳过10S开始播放就不会无缘无故的暂停了，你可以用TestViewController做实验，进来这个页面，改一下播放地址，然后run，起来后，拖进度条拖到10s左右，然后back，重新进来页面，播放就没问题了。
