### ISSUE TITLE
解决cell错乱的问题

### ISSUE THREAD

**Issue by lingtingSir** [zhengwenming/WMPlayer#6]
toCell方法中，    VideoCell *currentCell = [self currentCell];  改为
     VideoCell *currentCell = (VideoCell *)[self.table cellForRowAtIndexPath:[NSIndexPath indexPathForRow:currentIndexPath.row inSection:0]];

**Comment by zhengwenming** [comment]
代码已经修改，bug已经解决。谢谢你的支持。非常感谢。
