### ISSUE TITLE
currentItem移除观察者bug

### ISSUE THREAD

**Issue by zkil** [zhengwenming/WMPlayer#60]
在对象销毁执行dealloc，移除观察者
//移除观察者
    [_currentItem removeObserver:self forKeyPath:@"status"];
    [_currentItem removeObserver:self forKeyPath:@"loadedTimeRanges"];
    [_currentItem removeObserver:self forKeyPath:@"playbackBufferEmpty"];
    [_currentItem removeObserver:self forKeyPath:@"playbackLikelyToKeepUp"];
   此时已经移除了观察者
后，代码对currentItem置空self.currentItem = nil; 由于代码重写了set方法又一次移除观察者，导致奔溃

**Comment by zhengwenming** [comment]
谢谢您的提议，我已经修改了dealloc中的代码改为_currentItem  = nil；
再次感谢你对WMPlayer的贡献。
