### ISSUE TITLE
初始化播放器的高度不是屏幕宽度的0.75倍会导致已经播放进度条下移(和视频总长度不重合)

### ISSUE THREAD

**Issue by phasewong** [zhengwenming/WMPlayer#63]
playerFrame = CGRectMake(0, 0, SCREEN_WIDTH, (SCREEN_WIDTH * 9 / 16));
    wmPlayer = [WMPlayer new];
    wmPlayer.delegate = self;
    wmPlayer.URLString = self.URLString;
    wmPlayer.titleLabel.text = @"测试测试测试";
    wmPlayer.closeBtn.hidden = NO;
    [self.view addSubview:wmPlayer];
    [wmPlayer play];
    [wmPlayer mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.view).with.offset(0);
        make.left.equalTo(self.view).with.offset(0);
        make.right.equalTo(self.view).with.offset(0);
        make.height.equalTo(@(playerFrame.size.height));
    }];

**Comment by phasewong** [comment]
PS:请问可以用七牛的播放器 替换掉AVPlayer吗?毕竟AVPlayer支持的格式还是有限制的

**Comment by zhengwenming** [comment]
首先感谢您的使用和反馈
第一个问题或者bug，我会调试一下，确认是bug后会尽快修复（怀疑可能是约束的问题导致的）
第二个问题，关于七牛的播放器，如果你想用七牛的播放器，那么不能和我的这个进行关联，替换，然后用七牛的播放器心，用我的播放器的壳。

PS：关于AVPlayer播放格式少的问题，可以使用B站开源的ijkPlayer，基于ffmpeg这个技术的，可以满足你的大部分播放要求，但是界面要自己开发，没有现成这么好看的界面。

**Comment by phasewong** [comment]
大神您好,看您最新demo中还没有解决播放进度条和视频长度条不重合问题,之前描述的是播放器的高度不是屏幕宽度的0.75倍会导致已经播放进度条下移,现在多次测试发现,0.75倍下最新的demo在Plus横屏状态下也会导致播放进度条下移;0.65倍下:Plus横竖屏均下移,iPhone7下竖屏一开始正常,进入横屏后再返回竖屏状态导致进度条下移(所有测试是在DetailViewController中的).
ps:视频加载失败后或者观看网络视频网络中断后能否在播放器中间加上一个refresh的按钮.

**Comment by zhengwenming** [comment]
别急，太多事情了，有人要支持pods，搞了好几天了。
是约束导致的不重合，下移。
至于你的新需求，都会考虑加上去的，别催，我头都大了。

**Comment by phasewong** [comment]
大神辛苦了,万分感谢!

**Comment by zhengwenming** [comment]
bug已经修复，请下载最新的WMPlayer
