### ISSUE TITLE
视频播放的问题

### ISSUE THREAD

**Issue by zww965539071** [zhengwenming/WMPlayer#68]
总体觉得界面卡，而且有个问题挺严重的，就是假如点击了某一个视频(B)让其播放，这个时候再点击其他的视频(C)进入到视频详情界面,让C播放一段时间后返回到主界面，这个时候(B)就会快速的播放，感觉是在快进。而且不知道是为什么播放完一个视频后控制台总在打印日志，感觉是什么没被释放。

**Comment by zhengwenming** [comment]
不要设计成跳转页面了重新开一个播放器，两个播放器一起播放，不要这样设计，我的demo只是个demo，不是项目，演示一下怎么用的而已。这个问题不严重。
另外后台打印乱七八糟的东西，百度一下，可以解决的，不是WMPlayer引起的。
不用担心有东西没释放，不要感觉，释放了就是释放了，没释放就是没释放。不要感觉什么没释放。如果没释放，请截图或者demo联系我。
