### ISSUE TITLE
重复循环播放

### ISSUE THREAD

**Issue by mzying2013** [zhengwenming/WMPlayer#70]
-(void)wmplayerFinishedPlay:(WMPlayer *)wmplayer{
    [wmplayer.player play];
}

我在delegate回调里面这样写的。可以循环播放，但是不知道是否会引起其它问题？
因为这个delegate回调以后，还执行一些其它的操作（seekToTime:）才把.state置为WMPlayerStateFinished的。

**Comment by zhengwenming** [comment]
目前应该不会有问题的，包括崩溃或者内存泄漏。
有问题及时issue我。谢谢！
