### ISSUE TITLE
没有看到拖动快进的功能

### ISSUE THREAD

**Issue by SuperManPLA** [zhengwenming/WMPlayer#77]
拖动进度条没有反应，拖不动，是bug吗

**Comment by zhengwenming** [comment]
拖不动应该就是bug了，demo中拖动不了吗？还是你集成项目中后拖不动？

**Comment by SuperManPLA** [comment]
demo和集成到项目中都拖不动

**Comment by SuperManPLA** [comment]
我甚至都禁用了跟随手势拖动的那个属性，但是还是拖不动，还有个问题是网络不好时缓冲的情况下，缓存了好多了也不会自动播放，需要点击暂停按钮再点击播放才可以

**Comment by SuperManPLA** [comment]
进度条不能拖动，iOS 10.2无法正常播放视频，并且在网络卡顿缓存的情况下一旦缓存成功后，会出现不能自动播放，需要点击暂停再播放才能播放，真心需要优化啊，根本没法用

**Comment by sfdux** [comment]
我也是demo和集成到项目中不能拖，stratDragSlide这个方法一直没调用

**Comment by zhengwenming** [comment]
可能是手势冲突了，把WMDragView删了，把WMPlayer的父类改回来，改成继承UIView。

**Comment by sfdux** [comment]
是的，我也发现是这个问题，dragwiew里面actiontouch那个手势冲突了

在 2017-03-11 14:14:13，"文明" <notifications@github.com> 写道：


可能是手势冲突了，把WMDragView删了，把WMPlayer的父类改回来，改成继承UIView。
