### ISSUE TITLE
在这里鼓励一下

### ISSUE THREAD

**Issue by Summeerr** [zhengwenming/WMPlayer#8]
能做出来却是技术了得，功能也十分强大。不过对于一个框架来说它的复用性并不是很好，继承这个类的话，可以实现，但是太多问题，所以希望还是再多多把代码封装进去

**Comment by zhengwenming** [comment]
首先十分感谢你的支持 。
这个是播放视频的工具类，不会做为基类给开发者继承，因为这个类功能很明确，没必要继承，如果有其他的特殊需求可以提出来给我，我到时候修改一下，去适配广大的开发者。这个工具类，里面模仿系统的某些特性（比如键盘的通知事件），把所有的事件都用通知的方式提供给开发者了，开发者可以很方便的处理自己的逻辑，没有逻辑则不需要注册通知。
谢谢你的issue，期待你的回复。
