### ISSUE TITLE
模拟器能播，真机不能播

### ISSUE THREAD

**Issue by wxq491216** [zhengwenming/WMPlayer#85]
相同的wifi，模拟器播能正常播放。
真机能够加载，有进度条显示，拖动也能显示视频图像，就是不播放。

**Comment by zhengwenming** [comment]
个别案例，可能是iOS 10的系统导致的。建议换台手机测试。PS：其他开发者很少（几乎没有）出现不能播放的情况。

**Comment by wxq491216** [comment]
使用xib方式初始化，UIViewController退出时，VC的dealloc接口被调用到，但wmplayer的dealloc没被调用，且视频还在后台播放。我只有在UIViewController中使用weak引用了wmplayer对象，会不会wmplayer内部存在着循环引用呢？

**Comment by zhengwenming** [comment]
dealloc中主动释放资源，直接调用方法releaseWMPlayer，参考demo中的releaseWMPlayer方法。
