### ISSUE TITLE
ios9系统播放会直接崩溃

### ISSUE THREAD

**Issue by lushengfu** [zhengwenming/WMPlayer#89]
self.player.automaticallyWaitsToMinimizeStalling = NO;
这个属性应该做一个版本判断,iOS9中AVPlayer没有这个属性,会报如下错误:
[AVPlayer setAutomaticallyWaitsToMinimizeStalling:]: unrecognized selector sent to instance 0x15f58c890

**Comment by zhengwenming** [comment]
好的，谢谢您的提醒。我马上更新一下

**Comment by zhengwenming** [comment]
已经更新，请下载最新demo
