### ISSUE TITLE
播放失败问题，具体看内容

### ISSUE THREAD

**Issue by HugoDou** [zhengwenming/WMPlayer#90]
正常按你给的方法播放视频，但是有时候点击播放视频走完initWMPlayer方法后直接走delloc方法，没有走creatWMPlayerAndReadyToPlay方法播放视频

**Comment by zhengwenming** [comment]
if (self.isInitPlayer == NO) {
        self.isInitPlayer = YES;
        [self creatWMPlayerAndReadyToPlay];
        [self.player play];
        self.playOrPauseBtn.selected = NO;
    }
如果已经初始化了播放器，就不在初始化，如果没有初始化播放器（或者曾经释放了），那么self.isInitPlayer就会是NO。就可以重新创建一次。
您说的，上面的问题，没走creatWMPlayerAndReadyToPlay这个方法，是因为你没有释放过
只有释放后，你再去用，才会重新创建。
PS；播放失败的链接贴一下，我可以帮你debug一下。

**Comment by HugoDou** [comment]
谢谢大神
视频链接：http://ocgig6vo9.bkt.clouddn.com/1/3/1491029206911_dst.m3u8
应该释放过了，我点击播放先走了delloc方法，还有，这个只要多点击几次就正常播放了，我也看看，是不是我初始化有问题

**Comment by lushengfu** [comment]
确实也遇到了同样的问题?概率性的,还在找原因

**Comment by HugoDou** [comment]
忘了来回这个问题，是我们的链接有问题，谢谢大佬帮忙
