### ISSUE TITLE
present问题

### ISSUE THREAD

**Issue by he19910913** [zhengwenming/WMPlayer#95]
你好，我是在播放器的DetailViewController 上 present 到另外一个控制器上 回来时 出现报错了 ，希望大神能解决一下🙏。报错的原因：'preferredInterfaceOrientationForPresentation '(7)' must match a supported interface orientation: 'portrait, landscapeLeft, landscapeRight'!'

**Comment by zhengwenming** [comment]
这个在rootViewcontroller中修改，不是播放器的bug，属于旋转屏的知识。
简单提示一下，不要用topViewController了，用presentationController属性。这个我实现过，可以做到的。针对demo，那么代码肯定是demo中的是对的，如果你拿到你的项目中，可能是不适合的，这个就要修改了，至于怎么修改，要看自己项目的结构和代码。
   if ([nav.presentationController isKindOfClass:[NSClassFromString(@"DetailViewController") class]]) {
        return UIInterfaceOrientationMaskAllButUpsideDown;
    }
