### ISSUE TITLE
视频播放变形

### ISSUE THREAD

**Issue by lypcliuli** [zhengwenming/WMPlayer#98]
你好，我用WMPlayer做好之后，播放视频变形了，在列表里播放，和全屏播放都是变形，视频里的人脸都扁了，有么有好的建议解决这个问题的吗。

**Comment by zhengwenming** [comment]
修改视频的填充模式

**Comment by zhengwenming** [comment]
你好，请更新到V5.0，最新版本。如有问题，及时联系我本人
