### ISSUE TITLE
视频播放进度条拖拽时会有跳动现象

### ISSUE THREAD

**Issue by zcvael** [zhengwenming/WMPlayer#99]
视频播放进度条拖拽时会有往回跳动的现象

**Comment by zhengwenming** [comment]
请问你用的版本是最新的版本吗？跳动问题去年2016年就解决了。
请更新最新版本测试！

**Comment by zcvael** [comment]
是最新的版本，今天也是下载的最新的demo试了下，拖动的时候还是先会跳动到原来的位置然后迅速到拖拽的位置！iPhone 6 Plus   iOS 10.3.2。麻烦大神帮忙看下。

**Comment by EwanJJ** [comment]
@zcvael 我试了,是这样的.

**Comment by zhengwenming** [comment]
请更新最新版本5.0.0
